[2025-03-27T22:23:35.004+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T22:23:35.027+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.extract_superstore_data manual__2025-03-27T22:23:30.150991+00:00 [queued]>
[2025-03-27T22:23:35.045+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.extract_superstore_data manual__2025-03-27T22:23:30.150991+00:00 [queued]>
[2025-03-27T22:23:35.047+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-27T22:23:35.088+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_superstore_data> on 2025-03-27 22:23:30.150991+00:00
[2025-03-27T22:23:35.094+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2025-03-27T22:23:35.101+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'extract_superstore_data', 'manual__2025-03-27T22:23:30.150991+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmp4cit8vjf']
[2025-03-27T22:23:35.104+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask extract_superstore_data
[2025-03-27T22:23:35.187+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.extract_superstore_data manual__2025-03-27T22:23:30.150991+00:00 [running]> on host 4a86752196bf
[2025-03-27T22:23:35.327+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='extract_superstore_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T22:23:30.150991+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T22:23:30.150991+00:00'
[2025-03-27T22:23:35.330+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-27T22:23:35.333+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-27T22:23:35.335+0000] {logging_mixin.py:190} INFO - Current task name:extract_superstore_data state:running start_date:2025-03-27 22:23:35.030088+00:00
[2025-03-27T22:23:35.337+0000] {logging_mixin.py:190} INFO - Dag name:superstore_dag and current dag run status:running
[2025-03-27T22:23:35.339+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T22:23:35.363+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 18, in extract_superstore_data
    df = hook.get_pandas_df(sql=query)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 399, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 101, in get_conn
    conn = self.connection
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 242, in connection
    self._connection = self.get_connection(self.get_conn_id())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mssql_maj_db` isn't defined
[2025-03-27T22:23:35.389+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-27T22:23:35.392+0000] {logging_mixin.py:190} INFO - Task start:2025-03-27 22:23:35.030088+00:00 end:2025-03-27 22:23:35.389093+00:00 duration:0.359005
[2025-03-27T22:23:35.394+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_superstore_data> dag:<DAG: superstore_dag> dagrun:<DagRun superstore_dag @ 2025-03-27 22:23:30.150991+00:00: manual__2025-03-27T22:23:30.150991+00:00, state:running, queued_at: 2025-03-27 22:23:30.229947+00:00. externally triggered: True>
[2025-03-27T22:23:35.396+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `mssql_maj_db` isn't defined
[2025-03-27T22:23:35.399+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=superstore_dag, task_id=extract_superstore_data, run_id=manual__2025-03-27T22:23:30.150991+00:00, execution_date=20250327T222330, start_date=20250327T222335, end_date=20250327T222335
[2025-03-27T22:23:35.441+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T22:23:35.444+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task extract_superstore_data (The conn_id `mssql_maj_db` isn't defined; 87)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 18, in extract_superstore_data
    df = hook.get_pandas_df(sql=query)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 399, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 101, in get_conn
    conn = self.connection
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 242, in connection
    self._connection = self.get_connection(self.get_conn_id())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mssql_maj_db` isn't defined
[2025-03-27T22:23:35.477+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T22:23:35.540+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T22:23:35.562+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
